tipo = input('digite algo:')
print ('o tipo primitivo dessa palavra é', type(tipo))
print ('so tem espaços? ', tipo.isspace())
print ('é um numero? ', tipo.isnumeric())
print ('é alfabetico?', tipo.isalpha())
print ('é um alfanumerico?', tipo.isalnum())
print ('esta em maiuscula?', tipo.isupper())
print ('esta em minusculo?', tipo.islower())
print ('esta capitalizada?', tipo.istitle())